[build]
  # On commente l'ancienne commande pour la garder en mémoire
  # command = "npm run build" 

  # Voici la nouvelle commande de débogage
  command = "ls -R" 

  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200